baseURL = 'https://www.elag.org/'
languageCode = 'en-us'
title = 'ELAG'
theme = 'whiteplain'

copyright = "&copy; Copyright 2024 ELAG"

# Header Menu
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Guidelines"
  identifier = "guidelines"
  url = "/guidelines/"
  weight = 2

[[menu.main]]
  name = "History"
  identifier = "history"
  url = "/history/"
  weight = 4


# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
